---
title: "Regresion Lineal Simple"
author: "Diego Pavez"
date: "15/6/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Importar el dataset
dataset = read.csv('Salary_Data.csv')
head(dataset)
```

```{r}
# Dividir los datos en conjunto de entrenamiento y conjunto de test
# install.packages("caTools")
library(caTools)
set.seed(123)
split = sample.split(dataset$Salary, SplitRatio = 2/3)
training_set = subset(dataset, split == TRUE)
testing_set = subset(dataset, split == FALSE)
```

```{r}
# Ajustar el modelo de regresión lineal simple con el conjunto de entrenamiento
regressor = lm(formula = Salary ~ YearsExperience,
               data = training_set)
```
```{r}
# Predecir resultados con el conjunto de test
y_pred = predict(regressor, newdata = testing_set)
head(y_pred, 10)

```
```{r}
library(ggplot2)
ggplot() +
  geom_point(aes(x = training_set$YearsExperience, y = training_set$Salary),
             colour = "red") +
  geom_line(aes(x = training_set$YearsExperience,
                y = predict(regressor, newdata = training_set)),
            colour = "blue") + 
  ggtitle("Sueldo vs Años de Experiencia (Conjunto de entrenamiento)") + 
  xlab("Anos de Experiencia") +
  ylab("Sueldo en $")

```
```{r}
library(ggplot2)
ggplot() +
  geom_point(aes(x = testing_set$YearsExperience, y = testing_set$Salary),
             colour = "red") +
  geom_line(aes(x = training_set$YearsExperience,
                y = predict(regressor, newdata = training_set)),
            colour = "blue") + 
  ggtitle("Sueldo vs Años de Experiencia (Conjunto de testing)") + 
  xlab("Anos de Experiencia") +
  ylab("Sueldo en $")
```

