---
title: "preprocesamiento"
author: "Diego Pavez"
date: "14/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dataset = read.csv('Data.csv')
head(dataset)
```

```{r}
#calculo de las medias para datos desconocidos
dataset$Age = ifelse(is.na(dataset$Age),
                     ave(dataset$Age, FUN = function(x) mean(x, na.rm = TRUE)), dataset$Age)

dataset$Salary = ifelse(is.na(dataset$Salary),
                     ave(dataset$Salary, FUN = function(x) mean(x, na.rm = TRUE)), dataset$Salary)

```

```{r}
#CODIFICAR DATOS CATEGORICOS

dataset$Country = factor(dataset$Country, 
                         levels = c("France", "Spain", "Germany"),
                         labels = c(1, 2, 3))
dataset$Purchased = factor(dataset$Purchased, 
                           level = c("No", "Yes"),
                           labels = c(0,1))

```

```{r}
#Dividir el dataset
library(caTools)
set.seed(123)
split = sample.split(dataset$Purchased, SplitRatio = 0.8)
training_set = subset(dataset, split == TRUE)
testing_set = subset(dataset, split == FALSE)
```
```{r}
#Escalado de valores -> es para que una variable no domine sobre otra
training_set[,2:3] = scale(training_set[,2:3])
testing_set[,2:3] = scale(testing_set[,2:3])

```

